version: '3.9' # Указываем версию стандарта Docker Compose

services: # Здесь мы перечисляем программы (сервисы), которые хотим запустить
  db: # Название нашего сервиса
    image: postgres:16-alpine # Говорим Докеру: "Скачай готовую официальную сборку базы PostgreSQL версии 16"
    container_name: cinema-db # Даем нашей запущенной базе понятное имя, чтобы легко находить её в списке
    environment: # Блок настроек (переменных окружения) для самой базы данных
      POSTGRES_USER: cinema_admin     # Создаем главного администратора базы с логином
      POSTGRES_PASSWORD: cinema_pass # Задаем ему надежный пароль
      POSTGRES_DB: cinema_db         # Указываем имя базы данных, которая создастся внутри

    ports:
      - "5432:5432" # Пробрасываем мостик: порт 5432 на вашем компьютере связывается с портом 5432 внутри Докера
                    # Благодаря этому ваш будущий код автотестов сможет достучаться до базы.

    volumes: # Настройка постоянной памяти
      - pgdata:/var/lib/postgresql/data # Говорим: "Сохраняй данные базы на жесткий диск, чтобы они не стирались при перезагрузке"

      # А это главная QA-магия автоматизации:
      - ./init:/docker-entrypoint-initdb.d
      # Мы привязываем нашу локальную папку './init' к специальной папке внутри PostgreSQL.
      # СУБД устроена так: при самом первом старте она заглядывает в эту папку и автоматически 
      # выполняет любой SQL-скрипт, который там лежит. Туда мы и подсунем наш schema.sql!

    healthcheck: # Проверка "здоровья" базы данных
      test: ["CMD-SHELL", "pg_isready -U cinema_admin -d cinema_db"] # Команда, которая проверяет, запустилась ли база внутри контейнера
      interval: 5s  # Проверять каждые 5 секунд
      timeout: 5s   # Ждать ответа не больше 5 секунд
      retries: 5    # Если 5 раз подряд база ответит ошибкой — значит, контейнер "болен"

volumes:
  pgdata: # Объявляем виртуальный диск для хранения данных, который использовали выше
